name: cenv
channels:
  - ome
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - appdirs
  - appnope
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - brotlipy
  - bzip2
  - ca-certificates
  - cctools
  - cctools_osx-64
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - colorama
  - conda
  - conda-build
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - debugpy
  - decorator
  - executing
  - expat
  - filelock
  - freetype
  - future
  - giflib
  - glob2
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - lazy_loader
  - lcms2
  - ld64
  - ld64_osx-64
  - lerc
  - libarchive
  - libblas
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblief
  - libllvm14
  - libopenblas
  - libpng
  - libsodium
  - libsqlite
  - libtiff
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - numpy
  - omero-py
  - openjpeg
  - openssl
  - packaging
  - parso
  - patch
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - platformdirs
  - pluggy
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-lief
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pysocks
  - python
  - python-dateutil
  - python-libarchive-c
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - requests
  - ripgrep
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - sigtool
  - six
  - soupsieve
  - stack_data
  - tapi
  - tk
  - toml
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeroc-ice36-python
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd

# prefix: /nfs/users/nfs_d/dh24/miniconda3/envs/cenv
